/* ================================================================
   data.js — بيانات العينة الواقعية
   ================================================================ */

const WI_DATA = {

  /* ── المستخدمون ── */
  users: {
    worker:                 { name: 'سالم بن ناصر الحارثي',   civil: '9012345678', phone: '96898765432', email: 'salem.h@gmail.com' },
    employer_delegate:      { name: 'خالد بن سعيد البلوشي',   civil: '9087654321', phone: '96891234567', email: 'khalid.b@company.com', company: 'مجموعة النور للإنشاءات', cr: '1234567' },
    injury_investigator:    { name: 'عائشة بنت محمد الرواحي', civil: '9055551111', phone: '96895551111', employeeId: 'SPF-0342' },
    injury_head:            { name: 'يوسف بن علي الشيباني',   civil: '9055552222', phone: '96895552222', employeeId: 'SPF-0210' },
    od_investigator:        { name: 'فاطمة بنت حمد الحجرية',  civil: '9055553333', phone: '96895553333', employeeId: 'SPF-0387' },
    od_head:                { name: 'أحمد بن سليم المعمري',   civil: '9055554444', phone: '96895554444', employeeId: 'SPF-0198' },
    sickleave_employee:     { name: 'مريم بنت سيف الكيومية',  civil: '9055555555', phone: '96895555555', employeeId: 'SPF-0421' },
    sickleave_head:         { name: 'حمد بن عيسى الغافري',    civil: '9055556666', phone: '96895556666', employeeId: 'SPF-0156' },
    disability_employee:    { name: 'نورة بنت سالم الزدجالية', civil: '9055557777', phone: '96895557777', employeeId: 'SPF-0456' },
    disability_head:        { name: 'بدر بن خميس العبري',     civil: '9055558888', phone: '96895558888', employeeId: 'SPF-0134' },
    committees_employee:    { name: 'سعاد بنت أحمد الريامية', civil: '9055559999', phone: '96895559999', employeeId: 'SPF-0512' },
    committees_head:        { name: 'محمد بن راشد الهنائي',   civil: '9055550000', phone: '96895550000', employeeId: 'SPF-0089' },
    licensing_employee:     { name: 'هدى بنت ناصر الوهيبية',  civil: '9066661111', phone: '96896661111', employeeId: 'SPF-0534' },
    licensing_head:         { name: 'طالب بن سعيد الحنبلي',   civil: '9066662222', phone: '96896662222', employeeId: 'SPF-0067' },
    hospital_delegate:      { name: 'منى بنت عبدالله الرحبية', civil: '9066663333', phone: '96896663333', email: 'mona@hospital.om' },
    institution_rapporteur: { name: 'أنس بن خلفان الجابري',   civil: '9066664444', phone: '96896664444', employeeId: 'SPF-0589' },
  },

  /* ── طلبات بدلات الانقطاع عن العمل ── */
  allowances: [
    {
      id: 'WI-2025-001234',
      type: 'إصابة عمل',
      subtype: 'حادث طريق',
      isRelapse: 'لا',
      status: 'قيد التحقيق — إصابات العمل',
      submitDate: '2025-01-10',
      lastUpdate: '2025-01-12 09:45',
      applicant: { name: 'سالم بن ناصر الحارثي', civil: '9012345678', role: 'العامل / المؤمن عليه / المواطن', phone: '96898765432', email: 'salem.h@gmail.com' },
      insured: { name: 'سالم بن ناصر الحارثي', civil: '9012345678', insurance: 'IN-20190045678', dob: '1985-06-15', gender: 'ذكر', nationality: 'عُماني', insuranceStatus: 'نشط', regDate: '2019-03-01', subType: 'إلزامي' },
      employer: { name: 'مجموعة النور للإنشاءات ش.م.م', cr: '1234567', establishment: 'EST-0087654', jobTitle: 'مهندس مدني', joinDate: '2019-03-01', location: 'مسقط — الخوض' },
      injury: { description: 'تعرّض العامل لحادث مروري أثناء توجهه من محل إقامته إلى موقع العمل الصباح الباكر على طريق السيب — الخوض، إذ اصطدمت سيارته بمركبة أخرى أدت إلى إصابته في الكتف الأيسر وكسر في الضلوع.', location: 'طريق السيب — الخوض، أمام بوابة المنطقة الصناعية', bodyPart: 'الكتف الأيسر والضلوع', witnesses: 'نعم', witnessNames: 'محمد بن سالم الريامي — زميل عمل', incidentDate: '2025-01-09' },
      attachments: [
        { id: 'att1', type: 'تقرير طبي أولي', name: 'تقرير_مستشفى_خولة.pdf', uploadDate: '2025-01-10', uploadedBy: 'سالم الحارثي', role: 'العامل', size: '1.2 MB', icon: 'pdf' },
        { id: 'att2', type: 'تقرير الشرطة', name: 'تقرير_شرطة_السيب.pdf', uploadDate: '2025-01-10', uploadedBy: 'سالم الحارثي', role: 'العامل', size: '0.8 MB', icon: 'pdf' },
        { id: 'att3', type: 'كشف حضور وانصراف', name: 'كشف_الحضور_يناير.pdf', uploadDate: '2025-01-10', uploadedBy: 'سالم الحارثي', role: 'العامل', size: '0.5 MB', icon: 'pdf' },
      ],
      notes: [
        { id: 'n1', author: 'سالم الحارثي', role: 'العامل', text: 'تم إرفاق جميع المستندات المطلوبة. أرجو سرعة المعالجة نظراً للوضع الصحي.', time: '2025-01-10 10:30' }
      ],
      investigation: null,
      fieldVisits: [],
      sickLeavePeriods: [],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: null,
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'سالم الحارثي', role: 'العامل', time: '2025-01-10 10:15', fromStatus: '', toStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', note: '', type: 'default' },
        { action: 'تم توجيه الطلب لقسم التحقيق في إصابات العمل', actor: 'النظام', role: 'آلي', time: '2025-01-10 10:16', fromStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', toStatus: 'قيد التحقيق — إصابات العمل', note: 'تم توجيهه تلقائياً بناءً على نوع الطلب', type: 'default' },
        { action: 'تم حجز الطلب', actor: 'عائشة الرواحي', role: 'موظف قسم التحقيق في إصابات العمل', time: '2025-01-12 09:45', fromStatus: 'قيد التحقيق — إصابات العمل', toStatus: 'قيد التحقيق — إصابات العمل', note: '', type: 'default' },
      ],
      assignedTo: 'عائشة الرواحي',
      checkedOutBy: 'عائشة الرواحي',
    },
    {
      id: 'WI-2025-001198',
      type: 'إصابة عمل',
      subtype: 'إصابة في موقع العمل',
      isRelapse: 'لا',
      status: 'بانتظار اعتماد رئيس قسم التحقيق في إصابات العمل',
      submitDate: '2025-01-05',
      lastUpdate: '2025-01-14 14:20',
      applicant: { name: 'حمد بن سلطان العزري', civil: '9023456789', role: 'العامل / المؤمن عليه / المواطن', phone: '96899876543', email: '' },
      insured: { name: 'حمد بن سلطان العزري', civil: '9023456789', insurance: 'IN-20170056789', dob: '1982-11-20', gender: 'ذكر', nationality: 'عُماني', insuranceStatus: 'نشط', regDate: '2017-07-01', subType: 'إلزامي' },
      employer: { name: 'شركة عُمان للحديد والصلب', cr: '2345678', establishment: 'EST-0054321', jobTitle: 'فني تشغيل آلات', joinDate: '2017-07-01', location: 'صحار — المنطقة الصناعية' },
      injury: { description: 'أثناء تشغيل ماكينة القطع الثقيلة، انزلقت قطعة معدنية وأصابت يد العامل اليمنى مما أدى إلى كسر في أصابع السبابة والوسطى.', location: 'قاعة الإنتاج الرئيسية — خط إنتاج 3', bodyPart: 'اليد اليمنى', witnesses: 'نعم', witnessNames: 'سعيد بن خميس المحرزي — مشرف الإنتاج', incidentDate: '2025-01-04' },
      attachments: [
        { id: 'att4', type: 'تقرير طبي أولي', name: 'تقرير_مشفى_صحار.pdf', uploadDate: '2025-01-05', uploadedBy: 'حمد العزري', role: 'العامل', size: '0.9 MB', icon: 'pdf' },
        { id: 'att5', type: 'تقرير السلامة والصحة المهنية', name: 'تقرير_حادثة_صحار.pdf', uploadDate: '2025-01-06', uploadedBy: 'خالد البلوشي', role: 'الشخص المفوض من جهة العمل', size: '1.5 MB', icon: 'pdf' },
      ],
      notes: [],
      investigation: {
        summary: 'بعد مراجعة المستندات المقدمة والاطلاع على تقرير السلامة والصحة المهنية وإفادة المشرف المباشر، تبيّن أن الحادثة وقعت أثناء ساعات العمل الرسمية وفي موقع العمل المعتمد. وأن العامل كان يؤدي مهامه الوظيفية المعتادة. لا يوجد ما يشير إلى إهمال أو مخالفة للتعليمات.',
        findings: 'الحادثة مستوفية لشروط إصابة العمل وفقاً للمادة (4) من اللائحة. لا توجد مؤشرات على تعمّد الإصابة أو تناول مواد مؤثرة على الوعي.',
        employeeRecommendation: 'موافقة',
        employeeNotes: 'يوصى بإحالة الطلب لقسم الإجازات المرضية بعد اعتماد رئيس القسم.',
        headNotes: null,
        headDecision: null,
      },
      fieldVisits: [
        { date: '2025-01-08', time: '10:00', reason: 'معاينة موقع الحادثة والتحقق من ملابسات الواقعة', staff: 'عائشة بنت محمد الرواحي، سليم بن راشد الغيلاني', summary: 'تم الاطلاع على موقع الحادثة وفحص الآلة المسببة للإصابة. تبيّن أن الآلة في وضع تشغيل اعتيادي وأن لوحات التحذير موجودة.', results: 'لا توجد مخالفات واضحة لمعايير السلامة في الموقع. الإصابة ناجمة عن ظرف طارئ غير متوقع.', attachments: ['صور_موقع_الحادثة.zip'] }
      ],
      sickLeavePeriods: [],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: null,
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'حمد العزري', role: 'العامل', time: '2025-01-05 08:30', fromStatus: '', toStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', note: '', type: 'default' },
        { action: 'توجيه لقسم التحقيق في إصابات العمل', actor: 'النظام', role: 'آلي', time: '2025-01-05 08:31', fromStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', toStatus: 'قيد التحقيق — إصابات العمل', note: '', type: 'default' },
        { action: 'إضافة زيارة ميدانية', actor: 'عائشة الرواحي', role: 'موظف قسم التحقيق في إصابات العمل', time: '2025-01-08 11:30', fromStatus: 'قيد التحقيق — إصابات العمل', toStatus: 'قيد التحقيق — إصابات العمل', note: 'تمت الزيارة الميدانية لمعاينة الموقع', type: 'default' },
        { action: 'رفع تقرير التحقيق لرئيس القسم', actor: 'عائشة الرواحي', role: 'موظف قسم التحقيق في إصابات العمل', time: '2025-01-14 14:20', fromStatus: 'قيد التحقيق — إصابات العمل', toStatus: 'بانتظار اعتماد رئيس قسم التحقيق في إصابات العمل', note: 'التوصية: موافقة على إصابة العمل', type: 'success' },
      ],
      assignedTo: 'عائشة الرواحي',
      checkedOutBy: null,
    },
    {
      id: 'WI-2025-001156',
      type: 'مرض مهني',
      subtype: 'الربو المهني',
      isRelapse: 'لا',
      status: 'قيد المراجعة من موظف قسم الإجازات المرضية',
      submitDate: '2024-12-20',
      lastUpdate: '2025-01-10 11:05',
      applicant: { name: 'أمينة بنت علي الخروصية', civil: '9034567890', role: 'العامل / المؤمن عليه / المواطن', phone: '96897654321', email: 'ameena.k@mail.com' },
      insured: { name: 'أمينة بنت علي الخروصية', civil: '9034567890', insurance: 'IN-20160067890', dob: '1980-03-08', gender: 'أنثى', nationality: 'عُمانية', insuranceStatus: 'نشط', regDate: '2016-09-01', subType: 'إلزامي' },
      employer: { name: 'مصنع الخليج للنسيج', cr: '3456789', establishment: 'EST-0023456', jobTitle: 'مشرفة خطوط الإنتاج', joinDate: '2016-09-01', location: 'الرسيل — المنطقة الصناعية' },
      injury: { description: 'بعد سنوات من التعرض للغبار والمواد الكيميائية في بيئة العمل، ظهرت أعراض الربو الحادة. التشخيص صادر من طبيب متخصص في الأمراض المهنية.', chemicalAgents: 'الغبار القطني، مواد كيميائية للتبييض، بخار الأصباغ', exposureDuration: '9 سنوات متواصلة', firstSuspicion: '2024-10-15', workEnvironment: 'مبنى مغلق مع تهوية غير كافية، معدلات الغبار تتجاوز الحدود المسموح بها وفق قياسات الجهات المختصة' },
      attachments: [
        { id: 'att6', type: 'تقرير طبي متخصص', name: 'تقرير_الربو_المهني.pdf', uploadDate: '2024-12-20', uploadedBy: 'أمينة الخروصية', role: 'العامل', size: '2.1 MB', icon: 'pdf' },
        { id: 'att7', type: 'قياسات البيئة المهنية', name: 'قياسات_غبار_المصنع.pdf', uploadDate: '2024-12-22', uploadedBy: 'فاطمة الحجرية', role: 'موظف قسم التحقيق في الأمراض المهنية', size: '3.4 MB', icon: 'pdf' },
      ],
      notes: [],
      investigation: {
        summary: 'تم التحقق من سجلات الرقابة الصحية للعمال، وسجلات قياسات البيئة، وتقارير الفحوصات الدورية. كما تم التواصل مع المشرف الطبي للمصنع.',
        findings: 'توجد دلالة واضحة على ارتباط مرض الربو بالتعرض المهني لمدة 9 سنوات. المرض مدرج في قائمة الأمراض المهنية المعتمدة. شروط المادة (7) من اللائحة مستوفاة.',
        employeeRecommendation: 'موافقة',
        employeeNotes: 'يُوصى بالموافقة وإحالة الطلب لقسم الإجازات المرضية.',
        headNotes: 'اطلعت على التقرير وهو موثّق ومكتمل. الموافقة على إحالة الطلب.',
        headDecision: 'اعتماد وتوجيه إلى قسم الإجازات المرضية',
      },
      fieldVisits: [],
      sickLeavePeriods: [],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: null,
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'أمينة الخروصية', role: 'العامل', time: '2024-12-20 14:00', fromStatus: '', toStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', note: '', type: 'default' },
        { action: 'توجيه لقسم التحقيق في الأمراض المهنية', actor: 'النظام', role: 'آلي', time: '2024-12-20 14:01', fromStatus: 'تم تقديم الطلب — بانتظار تعيين المحقق المختص', toStatus: 'قيد التحقيق — الأمراض المهنية', note: '', type: 'default' },
        { action: 'رفع تقرير التحقيق لرئيس القسم', actor: 'فاطمة الحجرية', role: 'موظف قسم التحقيق في الأمراض المهنية', time: '2024-12-30 16:45', fromStatus: 'قيد التحقيق — الأمراض المهنية', toStatus: 'بانتظار اعتماد رئيس قسم التحقيق في الأمراض المهنية', note: 'التوصية: موافقة', type: 'success' },
        { action: 'اعتماد وتوجيه لقسم الإجازات المرضية', actor: 'أحمد المعمري', role: 'رئيس قسم التحقيق في الأمراض المهنية', time: '2025-01-05 09:00', fromStatus: 'بانتظار اعتماد رئيس قسم التحقيق في الأمراض المهنية', toStatus: 'قيد المراجعة من موظف قسم الإجازات المرضية', note: 'اعتمدت التقرير وأحلته لقسم الإجازات المرضية', type: 'success' },
      ],
      assignedTo: 'مريم الكيومية',
      checkedOutBy: 'مريم الكيومية',
    },
    {
      id: 'WI-2025-001089',
      type: 'إصابة عمل',
      subtype: 'إصابة في موقع العمل',
      isRelapse: 'لا',
      status: 'معتمد',
      submitDate: '2024-11-15',
      lastUpdate: '2025-01-08 10:00',
      applicant: { name: 'سيف بن راشد المحروقي', civil: '9045678901', role: 'العامل / المؤمن عليه / المواطن', phone: '96896543210', email: '' },
      insured: { name: 'سيف بن راشد المحروقي', civil: '9045678901', insurance: 'IN-20150078901', dob: '1978-07-22', gender: 'ذكر', nationality: 'عُماني', insuranceStatus: 'نشط', regDate: '2015-01-01', subType: 'إلزامي' },
      employer: { name: 'شركة تقنيات الطاقة المتجددة', cr: '4567890', establishment: 'EST-0076543', jobTitle: 'فني صيانة', joinDate: '2015-01-01', location: 'بركاء' },
      injury: { description: 'سقوط من علو أثناء صيانة ألواح الطاقة الشمسية أدى إلى كسر في الساق اليسرى.', location: 'سطح المبنى الرئيسي — مشروع ألواح بركاء', bodyPart: 'الساق اليسرى', witnesses: 'نعم', witnessNames: 'طالب بن سعد العامري', incidentDate: '2024-11-14' },
      attachments: [
        { id: 'att8', type: 'تقرير طبي أولي', name: 'تقرير_مستشفى_بركاء.pdf', uploadDate: '2024-11-15', uploadedBy: 'سيف المحروقي', role: 'العامل', size: '1.1 MB', icon: 'pdf' },
        { id: 'att9', type: 'تقرير إجازة مرضية', name: 'اجازة_مرضية_30يوم.pdf', uploadDate: '2024-11-20', uploadedBy: 'مريم الكيومية', role: 'موظف قسم الإجازات المرضية', size: '0.6 MB', icon: 'pdf' },
        { id: 'att10', type: 'تقرير إجازة مرضية', name: 'اجازة_مرضية_15يوم_امتداد.pdf', uploadDate: '2024-12-22', uploadedBy: 'مريم الكيومية', role: 'موظف قسم الإجازات المرضية', size: '0.5 MB', icon: 'pdf' },
      ],
      notes: [],
      investigation: {
        summary: 'وقعت الإصابة أثناء العمل المعتاد. الأسباب: عدم استخدام حزام الأمان بشكل صحيح.',
        findings: 'إصابة عمل مستوفية للشروط.',
        employeeRecommendation: 'موافقة',
        employeeNotes: '',
        headNotes: 'مستوفية. تمت الموافقة.',
        headDecision: 'اعتماد وتوجيه إلى قسم الإجازات المرضية',
      },
      fieldVisits: [],
      sickLeavePeriods: [
        { id: 'sl1', from: '2024-11-14', to: '2024-12-13', days: 30, status: 'معتمدة', addedBy: 'مريم الكيومية', addedDate: '2024-11-20', note: '' },
        { id: 'sl2', from: '2024-12-14', to: '2024-12-28', days: 15, status: 'معتمدة', addedBy: 'مريم الكيومية', addedDate: '2024-12-22', note: 'امتداد الإجازة بناءً على تقرير طبي جديد' },
      ],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: { status: 'تم الصرف', periods: 2, totalDays: 45, totalAmount: 1250.000, lastDisbursement: '2025-01-05', nextDisbursement: null, stopReason: null },
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'سيف المحروقي', role: 'العامل', time: '2024-11-15 09:00', fromStatus: '', toStatus: 'تم تقديم الطلب', note: '', type: 'default' },
        { action: 'اعتماد وتوجيه للإجازات', actor: 'يوسف الشيباني', role: 'رئيس قسم التحقيق في إصابات العمل', time: '2024-11-18 11:00', fromStatus: 'بانتظار اعتماد رئيس قسم التحقيق', toStatus: 'قيد المراجعة من موظف قسم الإجازات المرضية', note: '', type: 'success' },
        { action: 'إضافة فترة إجازة مرضية — 30 يوماً', actor: 'مريم الكيومية', role: 'موظف قسم الإجازات المرضية', time: '2024-11-20 10:30', fromStatus: 'قيد المراجعة', toStatus: 'قيد المراجعة', note: 'من 14/11 إلى 13/12', type: 'default' },
        { action: 'اعتماد الفترة الأولى', actor: 'حمد الغافري', role: 'رئيس قسم الإجازات المرضية', time: '2024-11-21 09:00', fromStatus: 'بانتظار اعتماد رئيس قسم الإجازات المرضية', toStatus: 'معتمد', note: '', type: 'success' },
        { action: 'إضافة فترة إجازة امتداد — 15 يوماً', actor: 'مريم الكيومية', role: 'موظف قسم الإجازات المرضية', time: '2024-12-22 14:00', fromStatus: 'معتمد', toStatus: 'بانتظار اعتماد رئيس قسم الإجازات المرضية', note: 'امتداد بناءً على تقرير طبي', type: 'default' },
        { action: 'اعتماد الفترة الثانية', actor: 'حمد الغافري', role: 'رئيس قسم الإجازات المرضية', time: '2024-12-23 10:00', fromStatus: 'بانتظار اعتماد رئيس قسم الإجازات المرضية', toStatus: 'معتمد', note: '', type: 'success' },
        { action: 'تم صرف استحقاق الفترة الأولى', actor: 'النظام', role: 'آلي', time: '2024-12-05 00:00', fromStatus: 'معتمد', toStatus: 'معتمد', note: 'صرف 750 ريال عُماني', type: 'success' },
        { action: 'تم صرف استحقاق الفترة الثانية', actor: 'النظام', role: 'آلي', time: '2025-01-05 00:00', fromStatus: 'معتمد', toStatus: 'معتمد', note: 'صرف 500 ريال عُماني', type: 'success' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
    {
      id: 'WI-2024-000987',
      type: 'إصابة عمل',
      subtype: 'إصابة في موقع العمل',
      isRelapse: 'لا',
      status: 'تم رفض الطلب',
      submitDate: '2024-10-01',
      lastUpdate: '2024-11-15 16:30',
      applicant: { name: 'ليلى بنت سيف الحوسنية', civil: '9056789012', role: 'العامل / المؤمن عليه / المواطن', phone: '96895432109', email: '' },
      insured: { name: 'ليلى بنت سيف الحوسنية', civil: '9056789012', insurance: 'IN-20200089012', dob: '1990-12-10', gender: 'أنثى', nationality: 'عُمانية', insuranceStatus: 'نشط', regDate: '2020-05-01', subType: 'إلزامي' },
      employer: { name: 'دار الرعاية الصحية الخاصة', cr: '5678901', establishment: 'EST-0054321', jobTitle: 'ممرضة', joinDate: '2020-05-01', location: 'مطرح' },
      injury: { description: 'إصابة أثناء التعامل مع مريض غير متعاون.', location: 'جناح الطوارئ', bodyPart: 'الظهر', witnesses: 'لا', incidentDate: '2024-09-30' },
      attachments: [
        { id: 'att11', type: 'تقرير طبي أولي', name: 'تقرير_ليلى.pdf', uploadDate: '2024-10-01', uploadedBy: 'ليلى الحوسنية', role: 'العامل', size: '0.7 MB', icon: 'pdf' },
      ],
      notes: [],
      investigation: { summary: 'مراجعة التقارير والسجلات.', findings: 'لم تُثبَت علاقة سببية مباشرة بين الإجراء الطبي الاعتيادي والإصابة المزعومة. الشهود غير متوفرين.', employeeRecommendation: 'رفض', employeeNotes: 'لا تستوفي شروط إصابة العمل وفق الأدلة المتاحة.', headNotes: 'أتفق مع التقرير، الرفض مبرر.', headDecision: 'رفض مع تحديد السبب' },
      fieldVisits: [],
      sickLeavePeriods: [],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: null,
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'ليلى الحوسنية', role: 'العامل', time: '2024-10-01 12:00', fromStatus: '', toStatus: 'تم تقديم الطلب', note: '', type: 'default' },
        { action: 'رفض الطلب', actor: 'يوسف الشيباني', role: 'رئيس قسم التحقيق في إصابات العمل', time: '2024-11-15 16:30', fromStatus: 'بانتظار اعتماد رئيس قسم التحقيق', toStatus: 'تم رفض الطلب', note: 'السبب: عدم استيفاء شروط إصابة العمل — غياب الأدلة الكافية وعدم وجود شهود', type: 'danger' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
    {
      id: 'WI-2025-001301',
      type: 'إصابة عمل',
      subtype: 'إجهاد وإرهاق',
      isRelapse: 'لا',
      status: 'تم إعادة الطلب لاستيفاء البيانات',
      submitDate: '2025-01-18',
      lastUpdate: '2025-01-19 15:30',
      applicant: { name: 'راشد بن محمد الجابري', civil: '9067890123', role: 'العامل / المؤمن عليه / المواطن', phone: '96894321098', email: 'rashid.j@email.com' },
      insured: { name: 'راشد بن محمد الجابري', civil: '9067890123', insurance: 'IN-20180090123', dob: '1983-04-25', gender: 'ذكر', nationality: 'عُماني', insuranceStatus: 'نشط', regDate: '2018-11-01', subType: 'إلزامي' },
      employer: { name: 'بنك التنمية العُماني', cr: '6789012', establishment: 'EST-0098765', jobTitle: 'مدير فرع', joinDate: '2018-11-01', location: 'نزوى' },
      injury: { description: 'إرهاق شديد وضغط نفسي مزمن ناجم عن العمل لساعات طويلة تتجاوز 14 ساعة يومياً دون إجازات كافية.', chemicalAgents: '', exposureDuration: '', firstSuspicion: '2025-01-10', workEnvironment: '' },
      attachments: [],
      notes: [
        { id: 'n2', author: 'عائشة الرواحي', role: 'موظف قسم التحقيق في إصابات العمل', text: 'يرجى تقديم: تقرير طبي من طبيب متخصص، كشف الساعات الإضافية خلال الأشهر الثلاثة الماضية، شهادة المشرف المباشر.', time: '2025-01-19 15:30' }
      ],
      investigation: null,
      fieldVisits: [],
      sickLeavePeriods: [],
      referral: null,
      session: null,
      committeeDecision: null,
      disbursement: null,
      returnReason: 'المستندات المطلوبة: (1) تقرير طبي من طبيب متخصص في الأمراض المهنية، (2) كشف ساعات العمل الإضافية للأشهر الثلاثة الأخيرة، (3) شهادة من المشرف المباشر توضح طبيعة العمل وحجم المسؤوليات.',
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'راشد الجابري', role: 'العامل', time: '2025-01-18 16:00', fromStatus: '', toStatus: 'تم تقديم الطلب', note: '', type: 'default' },
        { action: 'إعادة الطلب لاستيفاء البيانات', actor: 'عائشة الرواحي', role: 'موظف قسم التحقيق في إصابات العمل', time: '2025-01-19 15:30', fromStatus: 'قيد التحقيق — إصابات العمل', toStatus: 'تم إعادة الطلب لاستيفاء البيانات', note: 'يرجى تقديم المستندات المحددة أعلاه', type: 'warning' },
      ],
      assignedTo: 'عائشة الرواحي',
      checkedOutBy: null,
    },
  ],

  /* ── طلبات منفعة الإعاقة ── */
  disability: [
    {
      id: 'DIS-2025-000234',
      status: 'تم تقديم طلب منفعة الأشخاص ذوي الإعاقة — بانتظار مراجعة موظف قسم الإعاقة والأمراض المستديمة',
      submitDate: '2025-01-15',
      lastUpdate: '2025-01-15 11:00',
      applicant: { name: 'خلود بنت سعيد الرواسية', civil: '9078901234', phone: '96893210987', email: '' },
      card: { number: 'DIS-CARD-0056789', status: 'سارية', activationDate: '2022-03-10', expiryDate: '2027-03-09', typeSD: 'إعاقة حركية — الأطراف السفلية', typeMOH: 'قصور حركي درجة ثانية', provenDate: '2022-02-01' },
      insurance: { status: 'نشط', regDate: '2020-01-15', subType: 'إلزامي', otherBenefits: 'لا يوجد' },
      attachments: [
        { id: 'datt1', type: 'صورة بطاقة الإعاقة', name: 'بطاقة_الاعاقة.pdf', uploadDate: '2025-01-15', uploadedBy: 'خلود الرواسية', role: 'العامل', size: '0.8 MB', icon: 'pdf' },
        { id: 'datt2', type: 'تقرير طبي', name: 'تقرير_طبي_حديث.pdf', uploadDate: '2025-01-15', uploadedBy: 'خلود الرواسية', role: 'العامل', size: '1.3 MB', icon: 'pdf' },
      ],
      notes: [],
      disbursement: null,
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'خلود الرواسية', role: 'العامل', time: '2025-01-15 11:00', fromStatus: '', toStatus: 'تم تقديم طلب منفعة الأشخاص ذوي الإعاقة', note: '', type: 'default' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
    {
      id: 'DIS-2024-000198',
      status: 'تم اعتماد الطلب — الصرف جارٍ',
      submitDate: '2024-08-20',
      lastUpdate: '2024-09-10 10:00',
      applicant: { name: 'عبدالله بن حمود الهاشمي', civil: '9089012345', phone: '96892109876', email: '' },
      card: { number: 'DIS-CARD-0045678', status: 'سارية', activationDate: '2020-06-15', expiryDate: '2025-06-14', typeSD: 'إعاقة بصرية جزئية', typeMOH: 'ضعف بصري درجة أولى', provenDate: '2020-05-01' },
      insurance: { status: 'نشط', regDate: '2018-06-01', subType: 'إلزامي', otherBenefits: 'لا يوجد' },
      attachments: [
        { id: 'datt3', type: 'صورة بطاقة الإعاقة', name: 'بطاقة_هاشمي.pdf', uploadDate: '2024-08-20', uploadedBy: 'عبدالله الهاشمي', role: 'العامل', size: '0.7 MB', icon: 'pdf' },
      ],
      notes: [],
      disbursement: { approved: true, approvalDate: '2024-09-10', monthlyDay: 18, status: 'الصرف جارٍ', expiryDate: '2025-06-14', stopReason: null, lastCheck: '2025-01-18' },
      timeline: [
        { action: 'تم تقديم الطلب', actor: 'عبدالله الهاشمي', role: 'العامل', time: '2024-08-20 09:00', fromStatus: '', toStatus: 'تم تقديم طلب منفعة الأشخاص ذوي الإعاقة', note: '', type: 'default' },
        { action: 'اعتماد الطلب', actor: 'بدر العبري', role: 'رئيس قسم الإعاقة والأمراض المستديمة', time: '2024-09-10 10:00', fromStatus: 'بانتظار اعتماد رئيس القسم', toStatus: 'تم اعتماد الطلب — الصرف جارٍ', note: 'تم التحقق من صحة البطاقة وسريانها', type: 'success' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
  ],

  /* ── تشخيصات الأمراض المستديمة الواردة ── */
  chronicIncoming: [
    {
      refId: 'CHR-IN-2025-00089',
      applicantName: 'نادية بنت ناصر الوقفية',
      civil: '9090123456',
      hospital: 'مستشفى السلطاني — مسقط',
      diagnosis: 'داء السكري من النوع الأول',
      provenDate: '2024-12-01',
      doctor: 'د. محمد بن حسين المنذري',
      expectedPath: 'مسار مباشر',
      hasRequest: false,
      requestId: null,
    },
    {
      refId: 'CHR-IN-2025-00078',
      applicantName: 'سعيد بن علي الحبسي',
      civil: '9001234567',
      hospital: 'مستشفى ابن سينا — نزوى',
      diagnosis: 'الفشل الكلوي المزمن',
      provenDate: '2024-11-20',
      doctor: 'د. فاطمة بنت خلفان الخروصية',
      expectedPath: 'مسار اللجان الطبية',
      hasRequest: true,
      requestId: 'CHR-2025-000156',
    },
  ],

  /* ── التظلمات ── */
  appeals: [
    {
      id: 'APP-2025-000067',
      originalRequestId: 'WI-2024-000987',
      originalRequestType: 'بدلات انقطاع عن العمل',
      status: 'تم تقديم طلب التظلم — بانتظار مراجعة موظف قسم اللجان الطبية',
      submitDate: '2025-01-10',
      lastUpdate: '2025-01-10 14:30',
      applicant: { name: 'ليلى بنت سيف الحوسنية', civil: '9056789012', role: 'العامل / المؤمن عليه / المواطن' },
      decision: { type: 'رفض', date: '2024-11-15', issuer: 'رئيس قسم التحقيق في إصابات العمل', details: 'رُفض الطلب لعدم استيفاء شروط إصابة العمل — غياب الأدلة الكافية وعدم وجود شهود.', knowledgeDate: '2024-11-20' },
      appealReason: 'القرار مخالف للأنظمة',
      appealDetails: 'لم يُؤخذ بعين الاعتبار شهادة المشرف المباشر الذي أكد وقوع الحادثة أثناء العمل. أرفق شهادة المشرف وتقريراً طبياً مفصلاً.',
      additionalNotes: '',
      attachments: [
        { id: 'aatt1', type: 'مستند داعم', name: 'شهادة_المشرف.pdf', uploadDate: '2025-01-10', uploadedBy: 'ليلى الحوسنية', role: 'العامل', size: '0.6 MB', icon: 'pdf' },
        { id: 'aatt2', type: 'تقرير طبي', name: 'تقرير_طبي_مفصل.pdf', uploadDate: '2025-01-10', uploadedBy: 'ليلى الحوسنية', role: 'العامل', size: '1.8 MB', icon: 'pdf' },
      ],
      notes: [],
      session: null,
      finalDecision: null,
      timeline: [
        { action: 'تم تقديم التظلم', actor: 'ليلى الحوسنية', role: 'العامل', time: '2025-01-10 14:30', fromStatus: '', toStatus: 'تم تقديم طلب التظلم', note: '', type: 'default' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
  ],

  /* ── طلبات الترخيص ── */
  licensing: [
    {
      id: 'LIC-2025-000034',
      requestType: 'جديد',
      status: 'تم تقديم طلب الترخيص / التجديد — بانتظار مراجعة موظف قسم التراخيص والرقابة',
      submitDate: '2025-01-12',
      lastUpdate: '2025-01-12 16:00',
      delegate: { name: 'منى بنت عبدالله الرحبية', civil: '9066663333', role: 'المفوض عن المستشفيات', phone: '96896663333', email: 'mona@hospital.om' },
      institution: { name: 'مستشفى الأمل التخصصي', cr: '7890123', crStatus: 'سارٍ', crExpiry: '2026-12-31', type: 'مستشفى خاص', address: 'طريق السيب — مسقط', governorate: 'مسقط — ولاية السيب', phone: '96824567890', email: 'info@amal-hospital.om', currentLicenseNo: null },
      doctors: [
        { name: 'د. خالد بن سالم الهاشمي', civil: '9011122233', specialty: 'جراحة العظام', role: 'رئيس', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. ريم بنت أحمد المعولية', civil: '9022233344', specialty: 'الطب الباطني', role: 'نائب رئيس', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. حسن بن علي السيابي', civil: '9033344455', specialty: 'طب الأمراض المهنية', role: 'عضو', confirmStatus: 'بانتظار التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. سمية بنت سيف الشهرية', civil: '9044455566', specialty: 'إعادة التأهيل', role: 'عضو', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
      ],
      verification: { totalDoctors: 4, confirmedDoctors: 3, minMet: false, duplicates: [] },
      attachments: [
        { id: 'latt1', type: 'سجل تجاري', name: 'سجل_تجاري_الأمل.pdf', uploadDate: '2025-01-12', uploadedBy: 'منى الرحبية', role: 'المفوض عن المستشفى', size: '1.2 MB', icon: 'pdf' },
        { id: 'latt2', type: 'شهادة اعتماد', name: 'شهادة_اعتماد_وزارة_الصحة.pdf', uploadDate: '2025-01-12', uploadedBy: 'منى الرحبية', role: 'المفوض عن المستشفى', size: '2.1 MB', icon: 'pdf' },
      ],
      notes: [],
      session: null,
      committeeDecision: null,
      activeLicense: null,
      timeline: [
        { action: 'تم تقديم طلب الترخيص', actor: 'منى الرحبية', role: 'المفوض عن المستشفى', time: '2025-01-12 16:00', fromStatus: '', toStatus: 'تم تقديم طلب الترخيص', note: '', type: 'default' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    },
    {
      id: 'LIC-2024-000198',
      requestType: 'تجديد',
      status: 'تم اعتماد الترخيص — الترخيص نشط',
      submitDate: '2024-06-01',
      lastUpdate: '2024-08-15 09:00',
      delegate: { name: 'طارق بن ناصر الزدجالي', civil: '9077778888', role: 'المفوض عن المستشفيات', phone: '96897778888', email: 'tariq@noor-hospital.om' },
      institution: { name: 'مستشفى النور التخصصي', cr: '8901234', crStatus: 'سارٍ', crExpiry: '2027-05-31', type: 'مستشفى خاص', address: 'شارع قابوس — مسقط', governorate: 'مسقط — ولاية بوشر', phone: '96824678901', email: 'info@noor-hospital.om', currentLicenseNo: 'LIC-INST-2022-0045' },
      doctors: [
        { name: 'د. سيف بن حمد المسكري', civil: '9055566677', specialty: 'جراحة العظام', role: 'رئيس', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. هند بنت علي الحارثية', civil: '9066677788', specialty: 'طب الأمراض المهنية', role: 'نائب رئيس', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. أسامة بن سالم الغيلاني', civil: '9077788899', specialty: 'الطب الباطني', role: 'عضو', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. لميس بنت خميس الرئيسية', civil: '9088899900', specialty: 'إعادة التأهيل', role: 'عضو', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
        { name: 'د. وائل بن صالح الحوسني', civil: '9099900011', specialty: 'الطب النفسي المهني', role: 'عضو', confirmStatus: 'تم التأكيد', duplicateCheck: 'لا يوجد تعارض' },
      ],
      verification: { totalDoctors: 5, confirmedDoctors: 5, minMet: true, duplicates: [] },
      attachments: [],
      notes: [],
      session: { id: 'SES-2024-0089', date: '2024-08-10', time: '10:00', members: [], quorum: true },
      committeeDecision: { type: 'اعتماد الترخيص', content: 'استوفت المؤسسة جميع الاشتراطات — 5 أطباء مؤكدون جميعهم بدون تعارض', date: '2024-08-10', signatories: [] },
      activeLicense: { number: 'LIC-INST-2024-0067', issueDate: '2024-08-15', expiryDate: '2027-08-14', months: 36 },
      timeline: [
        { action: 'تقديم طلب التجديد', actor: 'طارق الزدجالي', role: 'المفوض عن المستشفى', time: '2024-06-01 09:00', fromStatus: '', toStatus: 'تم تقديم طلب الترخيص', note: '', type: 'default' },
        { action: 'اعتماد وإصدار الترخيص', actor: 'طالب الحنبلي', role: 'رئيس قسم التراخيص والرقابة', time: '2024-08-15 09:00', fromStatus: 'تم اتخاذ القرار من اللجنة الطبية الإشرافية', toStatus: 'تم اعتماد الترخيص — الترخيص نشط', note: 'صدر الترخيص رقم LIC-INST-2024-0067', type: 'success' },
      ],
      assignedTo: null,
      checkedOutBy: null,
    }
  ],

  /* ── الجلسات ── */
  sessions: [
    {
      id: 'SES-2025-0112',
      type: 'عرض على مؤسسة صحية مرخصة',
      institution: 'مستشفى النور التخصصي',
      date: '2025-01-28',
      time: '09:00',
      status: 'مجدولة',
      casesCount: 4,
      completedDecisions: 0,
      quorum: false,
      members: [
        { name: 'د. سيف المسكري', specialty: 'جراحة العظام', role: 'رئيس', attendance: 'مجدول' },
        { name: 'د. هند الحارثية', specialty: 'طب الأمراض المهنية', role: 'نائب رئيس', attendance: 'مجدول' },
        { name: 'د. أسامة الغيلاني', specialty: 'الطب الباطني', role: 'عضو', attendance: 'مجدول' },
        { name: 'د. لميس الرئيسية', specialty: 'إعادة التأهيل', role: 'عضو', attendance: 'مجدول' },
        { name: 'د. وائل الحوسني', specialty: 'الطب النفسي المهني', role: 'عضو', attendance: 'مجدول' },
      ],
      minutes: '',
      cases: [
        { requestId: 'WI-2025-001156', name: 'أمينة الخروصية', type: 'بدلات انقطاع — مرض مهني', reason: 'تحديد فترة الإجازة المرضية المستحقة', decisionStatus: 'بانتظار القرار', decision: null },
      ],
      signatures: [],
    }
  ],

  /* ── مؤشرات لوحات البيانات ── */
  dashboardStats: {
    'injury-investigator': [
      { label: 'الطلبات الجديدة في انتظار التحقيق', value: 7, type: 'p' },
      { label: 'الطلبات التي حجزتها (Check-out)', value: 3, type: 'i' },
      { label: 'طلبات مُعادة لي من الرئيس', value: 1, type: 'd' },
      { label: 'طلبات أرسلتها للرئيس هذا الأسبوع', value: 5, type: 's' },
    ],
    'injury-head': [
      { label: 'بانتظار قراري', value: 5, type: 'p' },
      { label: 'طلبات اعتمدتها هذا الشهر', value: 18, type: 's' },
      { label: 'طلبات رُفضت هذا الشهر', value: 2, type: 'd' },
      { label: 'طلبات أعدتها للموظفين', value: 3, type: 'w' },
    ],
    'sickleave-employee': [
      { label: 'الطلبات قيد المراجعة', value: 9, type: 'p' },
      { label: 'فترات إجازة أضفتها هذا الأسبوع', value: 12, type: 's' },
      { label: 'طلبات في انتظار استعلام وزارة الصحة', value: 4, type: 'i' },
      { label: 'طلبات محالة للجان الطبية', value: 2, type: 'pu' },
    ],
    'disability-employee': [
      { label: 'طلبات منفعة الإعاقة الجديدة', value: 6, type: 'p' },
      { label: 'حالات أمراض مستديمة واردة', value: 3, type: 'i' },
      { label: 'طلبات بانتظار الاعتماد', value: 8, type: 'w' },
      { label: 'حالات إعادة تقييم مستحقة', value: 5, type: 'd' },
    ],
    'committees-employee': [
      { label: 'طلبات عرض واردة جديدة', value: 4, type: 'p' },
      { label: 'حالات محالة للمؤسسات الصحية', value: 11, type: 'i' },
      { label: 'تظلمات قيد المراجعة', value: 3, type: 'pu' },
      { label: 'جلسات مجدولة هذا الأسبوع', value: 2, type: 's' },
    ],
    'licensing-employee': [
      { label: 'طلبات ترخيص جديدة', value: 3, type: 'p' },
      { label: 'طلبات تجديد', value: 5, type: 'i' },
      { label: 'تراخيص منتهية قريباً (30 يوم)', value: 2, type: 'w' },
      { label: 'زيارات رقابية مجدولة', value: 4, type: 's' },
    ],
    'institution-rapporteur': [
      { label: 'الجلسات المجدولة هذا الشهر', value: 3, type: 'p' },
      { label: 'حالات بانتظار إدخال القرار', value: 4, type: 'i' },
      { label: 'قرارات بانتظار التوقيع', value: 2, type: 'w' },
      { label: 'جلسات أُغلقت هذا الشهر', value: 5, type: 's' },
    ],
  }
};
